Models/Calculadora.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace webapp.Models
{
    public class Calculadora
    {
        public int Operador1 {get;set;}
        public int Operador2 {get;set;}

        public string Operando {get;set;}
    }
}

Models/Contacto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace webapp.Models
{
    public class Contacto
    {
        [Display(Name = "Name")]
        public string? Name {get; set; }
        [EmailAddress]
        [Display(Name = "Correo", Prompt = "example@example.org")]
        public string? Email {get; set; }
        [Phone]
        [Display(Name = "Telefono",Prompt = "999-999-999y")]
        public string? Phone {get; set; }
        [MinLength(5)]
        [MaxLength(1024)]
        [Display(Name = "Comentario")]
        public string? Description {get; set; }

    }
}

Models/ErrorViewModel.cs
namespace webapp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Factura.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace webapp.Models
{
    public class Factura
    {
        
    }
}

Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace webapp.Models
{
    public class Persona
    {
        
    }
}

Controllers/CalculadoraController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using webapp.Models;

namespace webapp.Controllers
{

    public class CalculadoraController : Controller
    {
        private readonly ILogger<CalculadoraController> _logger;

        public CalculadoraController(ILogger<CalculadoraController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Calcular(Calculadora objCalculadora)
        {
            double resultado = 0.00;
            
            if(objCalculadora.Operando =="+"){
                resultado = objCalculadora.Operador1 + objCalculadora.Operador2;

            }


            ViewData["Message"] = "El resultado es: "+ resultado;

            return View("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using webapp.Models;

namespace webapp.Controllers
{
   
    public class ContactoController : Controller
    {
        private readonly ILogger<ContactoController> _logger;

        public ContactoController(ILogger<ContactoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Contacto objContacto)
        {
            ViewData["Message"] ="Se registro satisfactoriamente";
            return View("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using webapp.Models;

namespace webapp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Calculadora/Index.cshtml
@model webapp.Models.Calculadora

<div class="text-center">
    <h1 class="display-4">Calculadora</h1>
    <form asp-controller="Calculadora" asp-action="Calcular">
        <input asp-for="Operador1" class="form-control" />
        <input asp-for="Operador2" class="form-control" />
        <select asp-for="Operando" class="form-control" >
            <option value="+">Suma</option>
            <option value="-">Resta</option>
            <option value="*">Multiplica</option>
            <option value="/">Divide</option>
        </select>
        <button type="submit" class="btn btn-primary">Calcular</button> 
    </form>
    <h1>@ViewData["Message"]</h1>
</div>

Views/Contacto/Index.cshtml
@model webapp.Models.Contacto


<div class="text-center">
    <h1 class="display-4">Contactenos</h1>
    <form asp-controller="Contacto" asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <div class="form-group">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Phone" class="control-label"></label>
            <input asp-for="Phone" class="form-control"  />
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control" ></textarea>
        <button type="submit" class="btn btn-primary">Crear</button> 
    </form>
    <h1>@ViewData["Message"]</h1>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "PAGINA WEB";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h1 class="display-4">HOLA</h1>
    <h1 class="display-4">HOLA2</h1>
     <h1 class="display-4">Hola soy Loreley, Azure</h1>
    <h1 class="display-4">Deseo que me salga bien este cambio :*</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - webapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webapp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">webapp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Caluladora</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Index">Contacto</a>
                        </li>                                                  
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - webapp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>